title: Adam Giles
url: "https://adamgil.es"
baseurl: ""

markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    auto_ids: true
    syntax_highlighter: rouge

tracking_id: G-75PM7J5WXX

footer: yes
footer_url: "https://github.com/giqles/giqles.github.io"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Contact"
   link: "/contact"
 - name: "Notes"
   link: "/notes"
 - name: "Presentations"
   link: "/presentations"
 - name: "Recipes"
   link: "/recipes"

jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      layout: default
      author: Adam Giles
      comments: true
      title:

disqus:
  shortname: adam-giles
