title: Researcher
url: "https://adamgil.es"
baseurl: ""

markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    auto_ids: true
    syntax_highlighter: rouge

tracking_id: #

footer: yes
footer_url: "https://github.com/giqles/giqles.github.io"
footer_text: "Forked from a design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass
