title: Adam Giles
url: "https://adamgil.es"
baseurl: ""

markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    auto_ids: true
    syntax_highlighter: rouge

tracking_id: UA-122038209-1

footer: yes
footer_url: "https://github.com/giqles/giqles.github.io"
# footer_text: "&copy; Adam Giles 2020" -- just shoved this
# straight into _layouts/default.html

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Contact"
   link: "/contact"
 - name: "Notes"
   link: "/notes"

jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      layout: default
      author: Adam Giles
      comments: true
      title:

disqus:
  shortname: adam-giles